add types to Inversion.inverse parameters
With v1.3.0, I'm getting TypeScript build failures when noImplicitAny is set to true.

```
node_modules/@flatten-js/core/index.d.ts:549:17 - error TS7006: Parameter 'Point' implicitly has an 'any' type.

549         inverse(Point) : Point;
                    ~~~~~

node_modules/@flatten-js/core/index.d.ts:550:17 - error TS7006: Parameter 'Line' implicitly has an 'any' type.

550         inverse(Line) : Line | Circle;
                    ~~~~

node_modules/@flatten-js/core/index.d.ts:551:17 - error TS7006: Parameter 'Circle' implicitly has an 'any' type.

551         inverse(Circle) : Line | Circle;
```

This PR adds explicit type annotations to the parameters for `Inversion.inverse`